// This file is auto-generated by @hey-api/openapi-ts

export type Ulid = string;

export type RegistrationPolicy = {
    studentIdPattern: '^[A-Z]{2}[0-9]{7,8}$';
    studentIdHint: 'Two uppercase letters followed by 7 or 8 digits';
    inputMode: 'text';
    studentIdMaxLength: 10;
    fullNameMaxLength: 128;
};

export type State = 'open' | 'closed';

export type ParticipantState = 'anonymous' | 'returning';

export type ResolveJoinCodeResponse = {
    quizSessionId: Ulid;
    state: 'open' | 'closed';
    participantState: 'anonymous' | 'returning';
    registrationPolicy: RegistrationPolicy;
};

export type RegisterParticipantRequest = {
    fullName: string;
    studentIdNumber: string;
};

export type Outcome = 'created' | 'rejoined';

export type RegisterParticipantResponse = {
    quizSessionId: Ulid;
    participantId: Ulid;
    outcome: 'created' | 'rejoined';
};

export type SubmitAnswerRequest = {
    selectedOptionId: Ulid;
};

export type SubmitAnswerResponse = {
    outcome: 'accepted' | 'already-accepted';
    selectedOptionId: Ulid;
};

export type QuizAppProblemCode = 'quiz.session-not-found' | 'quiz.unavailable' | 'quiz.session-closed' | 'registration.invalid-name' | 'registration.invalid-student-id' | 'question.closed' | 'answer.invalid-option';

export type FieldViolation = {
    /**
     * JSON Pointer to the invalid request field
     */
    pointer: string;
    message: string;
};

export type QuizAppProblem = {
    status: number;
    code: QuizAppProblemCode;
    title: string;
    detail?: string | null;
    fieldViolations?: Array<FieldViolation>;
};

export type QuizSessionId = Ulid;

export type PublicationId = Ulid;

export type ResolveJoinCodeData = {
    body?: never;
    path: {
        /**
         * Case-insensitive quiz join code.
         */
        joinCode: string;
    };
    query?: never;
    url: '/join-codes/{joinCode}';
};

export type ResolveJoinCodeErrors = {
    /**
     * `quiz.session-not-found`.
     */
    404: QuizAppProblem;
    /**
     * `quiz.unavailable`.
     */
    503: QuizAppProblem;
};

export type ResolveJoinCodeError = ResolveJoinCodeErrors[keyof ResolveJoinCodeErrors];

export type ResolveJoinCodeResponses = {
    /**
     * Resolved session and server-owned registration policy.
     */
    200: ResolveJoinCodeResponse;
};

export type ResolveJoinCodeResponse2 = ResolveJoinCodeResponses[keyof ResolveJoinCodeResponses];

export type RegisterParticipantData = {
    body: RegisterParticipantRequest;
    path: {
        quizSessionId: Ulid;
    };
    query?: never;
    url: '/quiz-sessions/{quizSessionId}/participants';
};

export type RegisterParticipantErrors = {
    /**
     * `quiz.session-closed`.
     */
    409: QuizAppProblem;
    /**
     * `registration.invalid-name` or `registration.invalid-student-id`, with field pointers.
     */
    422: QuizAppProblem;
    /**
     * `quiz.unavailable`.
     */
    503: QuizAppProblem;
};

export type RegisterParticipantError = RegisterParticipantErrors[keyof RegisterParticipantErrors];

export type RegisterParticipantResponses = {
    /**
     * Created or rejoined. Sets the participant session cookie.
     */
    200: RegisterParticipantResponse;
};

export type RegisterParticipantResponse2 = RegisterParticipantResponses[keyof RegisterParticipantResponses];

export type SubmitAnswerData = {
    body: SubmitAnswerRequest;
    path: {
        publicationId: Ulid;
    };
    query?: never;
    url: '/publications/{publicationId}/answers';
};

export type SubmitAnswerErrors = {
    /**
     * `question.closed`.
     */
    409: QuizAppProblem;
    /**
     * `answer.invalid-option`.
     */
    422: QuizAppProblem;
    /**
     * `quiz.unavailable`.
     */
    503: QuizAppProblem;
};

export type SubmitAnswerError = SubmitAnswerErrors[keyof SubmitAnswerErrors];

export type SubmitAnswerResponses = {
    /**
     * Authoritative accepted or already-accepted outcome.
     */
    200: SubmitAnswerResponse;
};

export type SubmitAnswerResponse2 = SubmitAnswerResponses[keyof SubmitAnswerResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/student/v1` | (string & {});
};