// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zUlid = z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);

export const zRegistrationPolicy = z.object({
    studentIdPattern: z.literal('^[A-Z]{2}[0-9]{7,8}$'),
    studentIdHint: z.literal('Two uppercase letters followed by 7 or 8 digits'),
    inputMode: z.literal('text'),
    studentIdMaxLength: z.literal(10),
    fullNameMaxLength: z.literal(128)
});

export const zResolveJoinCodeResponse = z.object({
    quizSessionId: zUlid,
    state: z.enum([
        'open',
        'closed'
    ]),
    participantState: z.enum([
        'anonymous',
        'returning'
    ]),
    registrationPolicy: zRegistrationPolicy
});

export const zRegisterParticipantRequest = z.object({
    fullName: z.string().min(1).max(128),
    studentIdNumber: z.string().min(9).max(10).regex(/^[A-Z]{2}[0-9]{7,8}$/)
});

export const zRegisterParticipantResponse = z.object({
    quizSessionId: zUlid,
    participantId: zUlid,
    outcome: z.enum([
        'created',
        'rejoined'
    ])
});

export const zSubmitAnswerRequest = z.object({
    selectedOptionId: zUlid
});

export const zSubmitAnswerResponse = z.object({
    outcome: z.enum([
        'accepted',
        'already-accepted'
    ]),
    selectedOptionId: zUlid
});

export const zQuizAppProblemCode = z.enum([
    'quiz.session-not-found',
    'quiz.unavailable',
    'quiz.session-closed',
    'registration.invalid-name',
    'registration.invalid-student-id',
    'question.closed',
    'answer.invalid-option'
]);

export const zFieldViolation = z.object({
    pointer: z.string(),
    message: z.string()
});

export const zQuizAppProblem = z.object({
    status: z.number().int().gte(400).lte(599),
    code: zQuizAppProblemCode,
    title: z.string(),
    detail: z.union([
        z.string(),
        z.null()
    ]).optional(),
    fieldViolations: z.array(zFieldViolation).optional()
});

export const zResolveJoinCodeResponse2 = zResolveJoinCodeResponse;

export const zRegisterParticipantResponse2 = zRegisterParticipantResponse;

export const zSubmitAnswerResponse2 = zSubmitAnswerResponse;