"""Arch integ-B coverage for A-REV-008: a real thumbnail worker process
(real GStreamer + PyGObject + webrtcbin), driven entirely over its stdin/
stdout signaling protocol — proving `set-remote-description` /
`create-answer` / `set-local-description` / ICE gathering all run for real
against a real GStreamer webrtcbin, and that a malformed control line or a
`close` message never crashes the worker (plan: "fake-worker WebRTC
signaling + crash cleanup").

The offer SDP below is a syntactically valid, hand-authored fixture rather
than one generated by a second `add-transceiver`+`create-offer` webrtcbin
client: that specific combination crashes inside this Arch build's
`libgstsdp`/`gst_sdp_message_copy` (verified independently of this
service's code — a native SDP-message-copy bug, not a `pipeline_manager`
bug). `set-remote-description` on text-parsed SDP, `create-answer`, and
`set-local-description` — the worker's actual code path — do not touch
that broken path at all, and are exercised for real here.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
import time
from pathlib import Path

import pytest

from pipeline_manager.pipelines.builder import ROLE_SOCKETS, PipelineSpec
from pipeline_manager.pipelines.platforms.rk3588 import RK3588Profile
from pipeline_manager.pipelines.thumbnails import (
    ThumbnailAnswer,
    ThumbnailIceOut,
    SourceRole,
    parse_worker_output_line,
    worker_argv,
    worker_graph,
)
from pipeline_manager.supervisor.health import HealthConfirmer
from pipeline_manager.supervisor.process import ProcessSupervisor
from pipeline_manager.supervisor.stop import STOP_DEADLINE_SECONDS, stop_process

pytestmark = pytest.mark.skipif(
    sys.platform == "win32" or shutil.which("gst-launch-1.0") is None,
    reason="requires a real GStreamer + PyGObject + webrtcbin install (Arch integ-b target, plan §3)",
)

PRESENTATION_SOCKET = ROLE_SOCKETS[SourceRole.PRESENTATION]

# A syntactically valid, self-contained recvonly video offer — the browser
# side of a real preview negotiation. Fixed ICE ufrag/pwd/fingerprint: this
# never has to actually complete a DTLS handshake for the signaling-loop
# assertions below.
_OFFER_SDP = """v=0
o=- 4611731400430051336 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE video0
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:aaaaaaaa
a=ice-pwd:bbbbbbbbbbbbbbbbbbbbbbbb
a=rtcp-mux
a=recvonly
a=rtpmap:96 H264/90000
a=mid:video0
a=fingerprint:sha-256 41:E5:62:FD:1B:7D:85:27:AF:BB:49:66:45:86:58:63:68:4D:40:3C:6D:45:84:C1:2F:EB:98:7F:05:8A:B8:F6
"""


class _SoftwareEncoderPlatform(RK3588Profile):
    """Same shape as `RK3588Profile`, `x264enc` instead of `mpph264enc` —
    the RK-hardware encoder isn't available off the board (plan §3)."""

    def encoder(self, profile):
        return ["x264enc", "speed-preset=ultrafast", "tune=zerolatency", f"bitrate={profile.video_bitrate_bps // 1000}"]


def _start_warm_presentation_writer() -> subprocess.Popen:
    Path(PRESENTATION_SOCKET).unlink(missing_ok=True)
    return subprocess.Popen(
        [
            "gst-launch-1.0", "-e",
            "videotestsrc", "is-live=true", "pattern=smpte", "!",
            "video/x-raw,format=NV12,width=1920,height=1080,framerate=60/1", "!",
            "shmsink", f"socket-path={PRESENTATION_SOCKET}", "wait-for-connection=false", "shm-size=64000000",
        ],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )


def _stop_writer(writer: subprocess.Popen) -> None:
    writer.terminate()
    try:
        writer.wait(timeout=5)
    except Exception:
        writer.kill()
    Path(PRESENTATION_SOCKET).unlink(missing_ok=True)


class _RealConfirmer:
    async def confirm(self, process, *, is_record=False, output_path=None, timeout=20.0, **_):
        await HealthConfirmer(poll_interval=0.05).confirm(
            process, is_record=is_record, output_path=output_path, timeout=timeout
        )


def _read_outbound_messages(process, *, timeout: float, want_types: set[str]) -> dict[str, object]:
    found: dict[str, object] = {}
    deadline = time.monotonic() + timeout
    seen = 0
    while time.monotonic() < deadline and not want_types.issubset(found.keys()):
        lines = process.raw_lines[seen:]
        seen += len(lines)
        for line in lines:
            message = parse_worker_output_line(line)
            if message is not None and message.type not in found:
                found[message.type] = message
        time.sleep(0.05)
    return found


@pytest.mark.asyncio
async def test_real_offer_produces_a_real_answer_and_ice_candidates(tmp_path) -> None:
    writer = _start_warm_presentation_writer()
    time.sleep(0.5)

    graph = worker_graph(SourceRole.PRESENTATION, _SoftwareEncoderPlatform())
    spec = PipelineSpec(argv=worker_argv(graph=graph), required_roles=(SourceRole.PRESENTATION,), encode_slots=1, outputs=())

    supervisor = ProcessSupervisor()
    process = await supervisor.start(spec, "thumbnails:integ-b")
    try:
        await _RealConfirmer().confirm(process, is_record=False, timeout=20.0)
        pgid_before = process.pgid

        offer_line = json.dumps(
            {"type": "offer", "negotiation_id": "n-integ-b", "role_id": "presentation", "sdp": _OFFER_SDP}
        )
        process.popen.stdin.write(offer_line + "\n")
        process.popen.stdin.flush()

        found = _read_outbound_messages(process, timeout=10.0, want_types={"answer", "ice"})

        assert "answer" in found, "worker never produced an SDP answer"
        answer = found["answer"]
        assert isinstance(answer, ThumbnailAnswer)
        assert answer.negotiation_id == "n-integ-b"
        assert "m=video" in answer.sdp
        assert "a=rtpmap:96 H264" in answer.sdp

        assert "ice" in found, "worker never gathered a local ICE candidate"
        ice = found["ice"]
        assert isinstance(ice, ThumbnailIceOut)
        assert ice.negotiation_id == "n-integ-b"
        assert ice.candidate  # non-empty candidate line

        assert process.pgid == pgid_before  # one worker, whole negotiation

        close_line = json.dumps({"type": "close", "negotiation_id": "n-integ-b"})
        process.popen.stdin.write(close_line + "\n")
        process.popen.stdin.flush()

        result = await stop_process(process, STOP_DEADLINE_SECONDS)
        assert result.clean_eos is True
    finally:
        if process.popen.poll() is None:
            process.popen.kill()
        process.popen.wait(timeout=5)
        supervisor.forget("thumbnails:integ-b")
        _stop_writer(writer)


@pytest.mark.asyncio
async def test_malformed_control_lines_do_not_crash_the_worker() -> None:
    """plan: 'fake-worker WebRTC signaling + crash cleanup' — garbage input
    on stdin must be ignored, not bring the process down."""
    writer = _start_warm_presentation_writer()
    time.sleep(0.5)

    graph = worker_graph(SourceRole.PRESENTATION, _SoftwareEncoderPlatform())
    spec = PipelineSpec(argv=worker_argv(graph=graph), required_roles=(SourceRole.PRESENTATION,), encode_slots=1, outputs=())

    supervisor = ProcessSupervisor()
    process = await supervisor.start(spec, "thumbnails:integ-b-2")
    try:
        await _RealConfirmer().confirm(process, is_record=False, timeout=20.0)

        for garbage in ("not json", "{}", '{"type": "unknown"}', '{"type": "offer"}'):
            process.popen.stdin.write(garbage + "\n")
        process.popen.stdin.flush()
        time.sleep(0.5)

        assert process.popen.poll() is None  # still alive after garbage input

        result = await stop_process(process, STOP_DEADLINE_SECONDS)
        assert result.clean_eos is True
    finally:
        if process.popen.poll() is None:
            process.popen.kill()
        process.popen.wait(timeout=5)
        supervisor.forget("thumbnails:integ-b-2")
        _stop_writer(writer)
